base_url = "cybersafe-dls.fr"
title = "CyberSafe-DLS"
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true
default_language = "fr"


[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
logo = "https://cybersafe-dls.fr/img/logo_title.webp"
base_ressources_url = "https://cybersafe-dls.fr"
